### ISSUE TITLE
data format issue

### ISSUE THREAD

**Issue by mirkancal** [sereisoglu/Kedi#10]
<img width="864" alt="image" src="https://github.com/user-attachments/assets/fdcf2907-377d-41ba-9076-a31a5a6f02c3">

platform: screenshot macos but also ios
v: 1.1.5(19)

**Comment by sereisoglu** [comment]
Hey @mirkancal, thanks for reporting. 

I already fixed this. It is caused by a change in an unused field of the API: https://github.com/sereisoglu/Kedi/commit/ecf8594137061eaa31196085e16fa14f184595e4

I'm waiting for Apple to approve the version.
